# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch: 
      - arm
    goarm: 
      - 7
prerelease: auto
archives:
  -
    format: binary
    name_template: "{{ .Binary }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^minor:'