# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build: 
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
  test:
    machine: true
    steps: 
      - checkout
      - run: |
          wget https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz
          tar -xvf go1.15.1.linux-amd64.tar.gz
          sudo rm -r /usr/local/go
          sudo mv go /usr/local
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          go test ./ -coverprofile=coverage.txt -covermode=atomic
          bash <(curl -s https://codecov.io/bash)